[tool.poetry]
name = "spamscript"
version = "0.1.0"
description = ""
authors = ["tehgingergod <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Sphinx = "^3.5.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
